# -*- coding: utf-8 -*-
"""Text to image creating

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/tar697/de19fec81ee1a9f8dbbc06a76457be7e/welcome-to-colab.ipynb
"""

!pip install diffusers transformers torch accelerate safetensors

import torch
from diffusers import StableDiffusionPipeline

model_id = "runwayml/stable-diffusion-v1-5"

pipe = StableDiffusionPipeline.from_pretrained(model_id, torch_dtype=torch.float16)  # Correct usage
pipe.to("cuda")  #

prompt = "a futuristic robot playing a guitar"
image = pipe(prompt).images[0]
image.show()

import matplotlib.pyplot as plt
plt.imshow(image)