# -*- coding: utf-8 -*-
"""AI_story_generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/tar697/AI-story-generator-using-GPT-2/blob/main/AI_story_generator.ipynb

#**Project description**: This beginner-friendly project uses a pre-trained GPT-2 language model from Hugging Face to generate creative stories based on user prompts.
"""

# Install required packages
!pip install -q streamlit transformers pyngrok

# Save your Streamlit app as app.py
with open("app.py", "w") as f:
    f.write('''
import streamlit as st
from transformers import pipeline

st.set_page_config(page_title="AI Story Generator", page_icon="📚")

st.title("📚 AI Story Generator")
st.markdown("Type a creative prompt, and let the AI generate a story for you!")

genre = st.selectbox( "🎭 Choose a story genre:", ["Default", "Sci-Fi", "Comedy", "Horror", "Fantasy", "Mystery", "Romance"])

prompt = st.text_input("🖊️ Enter a story prompt:", "Once upon a time in space...")
length = st.slider("📏 Story Length (max tokens)", min_value=50, max_value=300, value=150, step=10)

if genre != "Default":
    styled_prompt = f"Write a {genre.lower()} story: {prompt}"
else:
    styled_prompt = prompt

if st.button("🚀 Generate Story"):
    with st.spinner("Creating your story..."):
        generator = pipeline("text-generation", model="gpt2")
        story = generator(prompt,max_length=length,num_return_sequences=1,temperature=0.85,top_k=50,top_p=0.92,repetition_penalty=1.5,no_repeat_ngram_size=3,do_sample=True
)[0]["generated_text"]
        st.subheader("📝 Generated Story:")
        st.write(story)
        st.download_button(label="📥 Download Story as TXT", data=story,file_name="ai_story.txt",mime="text/plain"
)
''')

!ngrok config add-authtoken your_token

from pyngrok import ngrok
ngrok.kill()  # ✅ This closes all old tunnels

import threading
import os

def run():
    os.system("streamlit run app.py")

thread = threading.Thread(target=run)
thread.start()

public_url = ngrok.connect("http://localhost:8501")
#public_url = ngrok.connect(port=8501)
print(f"🔗 Public URL: {public_url}")
